compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

nodeLinker: node-modules

packageExtensions:
  "@angular-devkit/build-angular@*":
    dependencies:
      webpack: ^5.0.0

yarnPath: .yarn/releases/yarn-4.9.2.cjs
