# Use local Yarn 4.9.1 binary
yarnPath: .yarn/releases/yarn-4.9.1.cjs

# Use node_modules linker for maximum compatibility with Angular
nodeLinker: node-modules

# Prevent use of global Yarn cache – ensures builds are local and reproducible
enableGlobalCache: false

# Balance compression and install speed for local + CI installs
compressionLevel: mixed

# Fail if dependencies or lockfile are out of sync – ideal for CI
enableImmutableInstalls: false

# Patch Angular CLI build issues due to missing peer deps
packageExtensions:
  "@angular-devkit/build-angular@*":
    dependencies:
      "webpack": "^5.0.0"

# Optional plugin configuration (for advanced usage)
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
#     spec: "@yarnpkg/plugin-interactive-tools"

# Optional security hardening (disable install scripts from remote tarballs)
# unsafeHttpWhitelist: []

# Optional: paths Yarn should ignore during dependency resolution
# ignoredPaths:
#   - "**/*.spec.ts"
#   - "**/__tests__/**"
